auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: SuoLong.com
url: http://loveqingyatou.github.io
feed: /atom.xml
author_info: <a href="http://loveqingyatou.github.io/">SuoLong</a>
